### ISSUE TITLE
Can't figure out a way to run your code with my own picture

### ISSUE THREAD

**Issue by alex83803** [nghia-vo/sarepy#1]
Dear Nghia Vo,

I am trying to test your code with my own image and didn't figure out a way to do it.

For instance, if I need to remove the artifacts on the file my_image.png, which command/chain of commands should I enter in my shell to obtain my_image_without_artifacts.png? 

I use VS Code and Anaconda.

Thank you very much for your support.

Kind regards

Alex

**Comment by davin83803** [comment]
I have forgotten to mention that I use VS Code and Anaconda.

**Comment by nghia-vo** [comment]
Hi Alex,
   You need to convert a png format image to a 2D array. You can do that using the function "load_image" as shown here: https://github.com/nghia-vo/vounwarp/blob/master/vounwarp/losa/loadersaver.py 
After removing artifacts, the image can be saved using the "save_image" function.

I copy the part you need here:

import os
import numpy as np
from PIL import Image
from scipy.misc import bytescale

def load_image(file_path):
    """
    Load data from an image.
    ---------
    Parameters - file_path: Path to the file.
    ---------
    Return:    - 2D array.
    """
    if ("\\" in file_path):
        raise ValueError(
            "Please use a file path following the Unix convention")
    mat = None
    try:
        mat = np.asarray(Image.open(file_path), dtype=np.float32)
    except IOError:
        print("No such file or directory: {}").format(file_path)
        raise
    if len(mat.shape) > 2:
        axis_m = np.argmin(mat.shape)
        mat = np.mean(mat, axis=axis_m)
    return mat

def save_image(file_path, mat, overwrite=True):
    """
    Save 2D data to an image.
    ---------
    Parameters: - file_path: Path to the file.
                - mat: 2D array.
                - overwrite: Overwrite the existing file if True.
    ---------
    Return:     - Updated file path.
    """
    if ("\\" in file_path):
        raise ValueError(
            "Please use a file path following the Unix convention")
    file_base, file_ext = os.path.splitext(file_path)
    if not ((file_ext == ".tif") or (file_ext == ".tiff")):
        mat = bytescale(mat)
    _create_folder(file_path)
    if not overwrite:
        file_path = _create_file_name(file_path)
    image = Image.fromarray(mat)
    try:
        image.save(file_path)
    except IOError:
        print("Couldn't write to file {}").format(file_path)
        raise
    return file_path

mat = load_image("C:/my_image.png")  # load image
import stripe_artifact_removal as sarepy # Load ring removal methods
mat_corrected = sarepy.remove_all_stripe(mat, 3, 41, 11)
save_image("C:/my_image_without_artifacts.png", mat_corrected)

**Comment by alex83803** [comment]
Hi Nghia,

Thanks a lot for your help!

You are the best.

We are currently making some tests with your code.

I wish you a nice day.

Kind regards 

Alex
