### ISSUE TITLE
Problem with Hdf5 file

### ISSUE THREAD

**Issue by hfahad** [nghia-vo/sarepy#10]
Hello,
congratulations on your nice work. I have a dataset of micro CT images but in hdf5 format not in tiff format.
Can you please explain how we can use the hdf5 format raw dataset in this library?

Thank you in advance.

Kind regards,
Hafiz

**Comment by nghia-vo** [comment]
Hi, Sarepy has been integrated into Algotom. You can read the following tutorials and examples how to read hdf5 and process data:
Tutorials:
https://algotom.readthedocs.io/en/latest/toc/section1/section1_2.html
https://algotom.readthedocs.io/en/latest/toc/section4/section4_2.html
https://algotom.readthedocs.io/en/latest/toc/section4/section4_5.html
Examples:
https://github.com/algotom/algotom/tree/master/examples/common_data_processing_workflow/minimal_scripts
https://github.com/algotom/algotom/tree/master/examples
