### ISSUE TITLE
Trying to use your awesome algorithm wit .bin image files

### ISSUE THREAD

**Issue by alex83803** [nghia-vo/sarepy#2]
Dear Nghia Vo,

I have made some tests with .png pictures (thanks to your great support two weeks ago). 
Unfortunately the algorithm do not remove the artifacts on my png pictures, I guess this is due to the file format and compression. 

I am currenty trying to import .bin image files (uint16 format, but I am not 100% sure about it) and run your algorithm. 

Here is a piece of the .bin image file code so you can maybe guess which .bin file format it is: 
de08 de08 de08 db08 db08 d808 dc08 dd08
dc08 db08 dc08 dc08 db08 dd08 dc08 dc08
dd08 de08 d908 d608 db08 dc08 d608 d708
da08 d808 da08 d908 d708 d808 d708 d908
db08 d708 d508 d408 d408 d608 d508 d608
d608 d708 d508 d408 d808 d808 d508 d908

I do not get the expected results and I guess I am doing something wrong with the way I import my binary file (wrong parameters or something similar).

Ideally I would like to import the binary image, use your algorithms to remove all artifacts, save a .bin corrected version of it, as well as a .png corrected version of it for visualisation.

my piece of code is as follow:

image = open("path_to_my_bin_file", "r") 
mat = np.fromfile(image, dtype=np.uint16) 
mat = np.random.randint(np.iinfo(np.uint16).max, size=(1000,1000)).astype(np.uint16)
import stripe_artifact_removal as sarepy 
mat_corrected = sarepy.remove_all_stripe(mat, 3, 81, 31)
mat_corrected.tofile('path_where_to_create_my_corrected_bin_file')
save_image("path_where_to_create_my_corrected_png_file", mat_corrected)

The png image I get after runing your code is an 100% noisy picture, I do not get what I am doing wrong (see attached png picture).

I would be extremely grateful I you could have a look at it and help me one last time :-).

Kind Regards

Alex

![testcorrected1](https://user-images.githubusercontent.com/17074383/52164567-bb223380-26f3-11e9-88c9-b5a815a4503b.png)

**Comment by nghia-vo** [comment]
You need to remove this line Alex
mat = np.random.randint(np.iinfo(np.uint16).max, size=(1000,1000)).astype(np.uint16)
It overwrites the loaded "mat" and gives u random values image.
Could u post the original image you want to clean stripe artfacts here? Note that my methods works on sinograms (a set of projections of a 2D object) not arbitrary images having stripe artifacts

**Comment by alex83803** [comment]
Thanks for your anser :-) you are right, it is a complete nonsense adding this line (I've realised it after I wrote you and it was already too late...)

I am confident that your code could work on the type of images I try to correct because they are optoacoustic images. 

When I remove the line you meant, I get the following error: 
 File "stripe_artifact_removal.py", line 233, in remove_unresponsive_and_fluctuating_stripe
  (nrow, _) = sinogram.shape
ValueError: not enough values to unpack (expected 2, got 1)

I've tried to replace it by 
mat = np.reshape(mat0, (-1, 8))

but it still doesn't work. 

The raw bin image is huge and I guess I cannot uplad it directly.

Thank you so much for having my back.

Alex

**Comment by alex83803** [comment]
![image](https://user-images.githubusercontent.com/17074383/52167501-1c5dfd00-271c-11e9-841a-28ee25405457.png)
For instance, if I try to run your algorithm on the image of your article, nothing happens.

This is the reason why I thought using a .bin raw data would improve the results.

**Comment by nghia-vo** [comment]
Alex, that's the reconstructed image. The methods should apply to sinograms. Do u have any experience with tomography?
Upload your image to Google drive and send link to my email. Cheers. Nghia

**Comment by alex83803** [comment]
Hi,

Thanks a lot for your Feedback :-). It has widened my thinking and brought me to a own solution :-). 

Kind regards

Alex
