### ISSUE TITLE
Error in matlab implementation (detect_stripe function)

### ISSUE THREAD

**Issue by grodgers1** [nghia-vo/sarepy#4]
Hi,

Thanks a lot for the great code and the useful paper! 

I am working with the version for Matlab and I think there may be an error having to do with the detect_stripe function:
lines 78 and 82 should instead read:
upper_thresh = numt1 + noiselevel * snr * 0.5;
lower_thresh = intercept - noiselevel * snr * 0.5;
(respectively)
The current version has "numt1" and "intercept" switched, which made the "listmask" all 1's because "upper_thresh" was less than 1 and "lower_thresh" was greater than 1. The root problem is that numt1>intercept because the default order for the sort function in Matlab is 'ascending'.

Thanks again,
Griffin

**Comment by nghia-vo** [comment]
Thanks for spotting that Griffin. There's mismatch between python and matlab code. I've fixed that on Dan's behaft.
