### ISSUE TITLE
Configuring sarepy as a python library 

### ISSUE THREAD

**Issue by decarlof** [nghia-vo/sarepy#5]
Nice toolbox! Would you be interested in configuring it as a python library? Let me know and I will give it a try through a pull request.

**Comment by nghia-vo** [comment]
@decarlof : Great! Thanks a lot Francesco.  This repo is mainly for demonstration and documentation purpose.  I plan to package the core of sarepy only (just ring removal methods, no input-output module and reconstruction module). I'll tag you when it comes online and please help then.

**Comment by decarlof** [comment]
@nghia-vo OK, would you also consider contributing the function to tomopy?

**Comment by nghia-vo** [comment]
@decarlof : already did :) https://tomopy.readthedocs.io/en/latest/api/tomopy.prep.stripe.html  
Not all of them, but most practical methods.

**Comment by dgursoy** [comment]
We should also create a ref in tomopy to this repo. Very nice tutorials on the topic!

**Comment by nghia-vo** [comment]
Thanks Doga, that would be great.

**Comment by nghia-vo** [comment]
sarepy has been integrated into Algotom (https://github.com/algotom/algotom) which is installable using pip and conda.
