### ISSUE TITLE
Black outputs

### ISSUE THREAD

**Issue by Madani-Irsa** [nghia-vo/sarepy#8]
Hi, 
First of all thanks for your great functional algorithms. 
There is a problem with the results when I make modifications in your code trying it with my own sinogram. The issue is that reconstructed tiff files (both before and after correction) are completely black showing nothing. In contrast, when I save my corrected sinogram the stripes are somewhat corrected and there is nothing wrong with that.
personally I thought of normalization to be a solution but I'm not sure. I wanted to know what can be the reason? and how to address it?

**Comment by nghia-vo** [comment]
Hello,
You're welcome.
There're two cases the output is black:
- There're values <=0 in the sinogram. In the reconstruction step, applying logarithm operation to this sinogram will result in NaN array. To fix this: sinogram[sinogram<=0] = 1.0
- The output is 32-bit tiff. Common photo software can't display 32-bit tiff. You need to use Imagej for viewing: https://imagej.nih.gov/ij/download.html. More detailed information is at here: https://algotom.github.io/toc/section1/section1_2.html#tiff-format

**Comment by Madani-Irsa** [comment]
Thanks for your help
