### ISSUE TITLE
Distortions introduced after correction

### ISSUE THREAD

**Issue by prog96** [nghia-vo/sarepy#9]
Hi,
I tried your code on your provided dataset and it worked really well.

However, there are a few lines (distortions) formed around the object after the ring artifacts removal as shown in red boxes on the image below. I used parameters of R = 3, la size of 81 and sm size of 31 in the figure (a). I increased R to 5 to remove some of the distortions in (b) but they are not entirely gone. I also changed the parameters of both la and sm sizes but it did not work too. Is there any other solution to this issue? 

Thank you in advance.

![image](https://user-images.githubusercontent.com/74073398/225286513-616b4513-eefb-44d3-936c-de16cb5f1271.png)

**Comment by nghia-vo** [comment]
The streak artifacts are the side-effect of sorting-based algorithms as explained here: https://sarepy.readthedocs.io/toc/section3_1/section3_1_1.html. You can try another method which only remove stripe artifacts inside a mask: https://sarepy.readthedocs.io/toc/section4/section4_2.html. This method however has its own disadvantage as it relies on the mask generator. In general, there's no perfect method. Remove_all_stripe is the combination of methods and they work well in most of cases : https://algotom.readthedocs.io/en/latest/toc/section4/section4_4.html. FYI, I would recommend to use these algorithms through Algotom as Sarepy was deprecated.

**Comment by prog96** [comment]
Thank you for the clarification!
